spring.application.name=kata-birthday

# profilo attivo (file / jpa / jdbc)
spring.profiles.active=file

spring.task.scheduling.shutdown.await-termination=true
spring.task.scheduling.shutdown.await-termination-period=1s